/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/tumbler.glb --types 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    tumbler_rubber: THREE.Mesh
    tumbler_body_stainless: THREE.Mesh
    tumbler_body: THREE.Mesh
    tumbler_lid: THREE.Mesh
    tumbler_lid_glass: THREE.Mesh
    tumbler_lid_stainless: THREE.Mesh
    tumbler_lid_rubber: THREE.Mesh
    tumbler_lid_black_obj: THREE.Mesh
    tumbler_lid_black_obj_1: THREE.Mesh
    tumbler_lid_icon: THREE.Mesh
    tumbler_lid_number: THREE.Mesh
    tumbler_body_filter_obj: THREE.Mesh
    tumbler_body_filter_obj_1: THREE.Mesh
  }
  materials: {
    material_rubber: THREE.MeshStandardMaterial
    material_body_stainless: THREE.MeshStandardMaterial
    material_body: THREE.MeshStandardMaterial
    material_lid: THREE.MeshStandardMaterial
    material_lid_glass: THREE.MeshPhysicalMaterial
    material_lid_stainless: THREE.MeshStandardMaterial
    material_lid_rubber: THREE.MeshStandardMaterial
    material_lid_black: THREE.MeshStandardMaterial
    material_lid_black_1: THREE.MeshStandardMaterial
    material_lid_icon: THREE.MeshStandardMaterial
    material_lid_number: THREE.MeshStandardMaterial
    material_body_filter: THREE.MeshStandardMaterial
    material_body_filter_1: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/tumbler.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.tumbler_rubber.geometry} material={materials.material_rubber} />
      <mesh geometry={nodes.tumbler_body_stainless.geometry} material={materials.material_body_stainless} />
      <mesh geometry={nodes.tumbler_body.geometry} material={materials.material_body} />
      <mesh geometry={nodes.tumbler_lid.geometry} material={materials.material_lid} position={[0, -0.001, 0]} />
      <mesh geometry={nodes.tumbler_lid_glass.geometry} material={materials.material_lid_glass} position={[0, -0.001, 0]} />
      <mesh geometry={nodes.tumbler_lid_stainless.geometry} material={materials.material_lid_stainless} position={[0, -0.001, 0]} />
      <mesh geometry={nodes.tumbler_lid_rubber.geometry} material={materials.material_lid_rubber} position={[0, -0.001, 0]} />
      <group position={[0, -0.001, 0]}>
        <mesh geometry={nodes.tumbler_lid_black_obj.geometry} material={materials.material_lid_black} />
        <mesh geometry={nodes.tumbler_lid_black_obj_1.geometry} material={materials.material_lid_black_1} />
      </group>
      <mesh geometry={nodes.tumbler_lid_icon.geometry} material={materials.material_lid_icon} position={[0, -0.001, 0]} />
      <mesh geometry={nodes.tumbler_lid_number.geometry} material={materials.material_lid_number} position={[0, -0.001, 0]} />
      <mesh geometry={nodes.tumbler_body_filter_obj.geometry} material={materials.material_body_filter} />
      <mesh geometry={nodes.tumbler_body_filter_obj_1.geometry} material={materials.material_body_filter_1} />
    </group>
  )
}

useGLTF.preload('/tumbler.glb')
