/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/tumbler.glb --transform --keepnames --keepgroups 
Files: public/tumbler.glb [2.15MB] > C:\Programming Projects\Lucid\tumbler-transformed.glb [128.12KB] (94%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/tumbler-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        <mesh name="tumbler_rubber" geometry={nodes.tumbler_rubber.geometry} material={materials.PaletteMaterial001} />
        <mesh name="tumbler_lid_glass" geometry={nodes.tumbler_lid_glass.geometry} material={materials.PaletteMaterial002} position={[0, -0.001, 0]} />
        <mesh name="tumbler_lid_icon" geometry={nodes.tumbler_lid_icon.geometry} material={materials.PaletteMaterial003} position={[0, -0.001, 0]} />
        <mesh name="tumbler_lid_number" geometry={nodes.tumbler_lid_number.geometry} material={materials.PaletteMaterial004} position={[0, -0.001, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/tumbler-transformed.glb')
