/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/tumbler.glb --transform --types 
Files: public/tumbler.glb [2.15MB] > C:\Programming Projects\Lucid\tumbler-transformed.glb [128.12KB] (94%)
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import { useRef } from 'react'
import type { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    tumbler_rubber: THREE.Mesh
    tumbler_lid_glass: THREE.Mesh
    tumbler_lid_icon: THREE.Mesh
    tumbler_lid_number: THREE.Mesh
  }
  materials: {
    PaletteMaterial001: THREE.MeshStandardMaterial
    PaletteMaterial002: THREE.MeshPhysicalMaterial
    PaletteMaterial003: THREE.MeshStandardMaterial
    PaletteMaterial004: THREE.MeshStandardMaterial
  }
  animations: THREE.AnimationClip[]
}

export function Tumbler(props: any) {
  const { nodes, materials } = useGLTF('/tumbler.glb') as unknown as GLTFResult

  const rubberRef = useRef<THREE.Mesh>(null!)
  const glassRef = useRef<THREE.Mesh>(null!)
  const iconRef = useRef<THREE.Mesh>(null!)
  const numberRef = useRef<THREE.Mesh>(null!)

  useFrame((_state, delta) => {
    // Determine target positions based on isDisassembled prop
    // We move them along their local Y axis
    const tRubber = props.isDisassembled ? -0.15 : 0;
    const tGlass = props.isDisassembled ? 0.15 : -0.001;
    const tIcon = props.isDisassembled ? 0.3 : -0.001;
    const tNumber = props.isDisassembled ? 0.45 : -0.001;

    // Smoothly interpolate positions
    rubberRef.current.position.y = THREE.MathUtils.damp(rubberRef.current.position.y, tRubber, 6, delta);
    glassRef.current.position.y = THREE.MathUtils.damp(glassRef.current.position.y, tGlass, 6, delta);
    iconRef.current.position.y = THREE.MathUtils.damp(iconRef.current.position.y, tIcon, 6, delta);
    numberRef.current.position.y = THREE.MathUtils.damp(numberRef.current.position.y, tNumber, 6, delta);
  })

  console.log('nodes', nodes)

  return (
    <group {...props} dispose={null}>
      <mesh ref={rubberRef} geometry={nodes.tumbler_rubber.geometry} material={materials.PaletteMaterial001} />
      <mesh ref={glassRef} geometry={nodes.tumbler_lid_glass.geometry} material={materials.PaletteMaterial002} position={[0, -0.001, 0]} />
      <mesh ref={iconRef} geometry={nodes.tumbler_lid_icon.geometry} material={materials.PaletteMaterial003} position={[0, -0.001, 0]} />
      <mesh ref={numberRef} geometry={nodes.tumbler_lid_number.geometry} material={materials.PaletteMaterial004} position={[0, -0.001, 0]} />
    </group>
  )
}


useGLTF.preload('/tumbler-transformed.glb')

export default Tumbler
